<h1>Data Understanding

In [2]:
# Imports
import pandas as pd
import numpy as np

In [3]:

# Load data 
ds = pd.read_csv('C:\\Users\\aSUS\\Documents\\IMS\\Master Data Science and Advanced Analytics with major in BA\\2nd Semestre\\Business Cases with Data Science\\Class 3\\Dataset.csv',sep=';')
ds.head()
# we have 41188 instances and 21 columns.

,ID,Nationality,Age,DaysSinceCreation,NameHash,DocIDHash,AverageLeadTime,LodgingRevenue,OtherRevenue,BookingsCanceled,...,SRMediumFloor,SRBathtub,SRShower,SRCrib,SRKingSizeBed,SRTwinBed,SRNearElevator,SRAwayFromElevator,SRNoAlcoholInMiniBar,SRQuietRoom
0,1,PRT,52.0,440,0x2C371FD6CE12936774A139FD7430C624F1C4D5109CE6...,0x434FD3D59469C73AFEA087017FAF8CA2296493AEABDE...,59,292.0,82.3,1,...,0,0,0,0,0,0,0,0,0,0
1,2,PRT,NaN,1385,0x198CDB98BF37B6E23F9548C56A88B00912D65A9AA0D6...,0xE3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B...,61,280.0,53.0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,DEU,32.0,1385,0xDA46E62F66936284DF2844EC4FC542D0DAD780C0EE0C...,0x27F5DF762CCDA622C752CCDA45794923BED9F1B66300...,0,0.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,FRA,61.0,1385,0xC45D4CD22C58FDC5FD0F95315F6EFA5A6E7149187D49...,0x8E59572913BB9B1E6CAA12FA2C8B7BF387B1D1F3432E...,93,240.0,60.0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,FRA,52.0,1385,0xD2E3D5BFCA141865669F98D64CDA85AD04DEFF47F8A0...,0x42BDEE0E05A9441C94147076EDDCC47E604DA5447DD4...,0,0.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
# Summary statistics for all variables
summary=ds.describe(include='all') # so that it includes categorical variables
summary=summary.transpose() # to read easily
summary.head(len(summary))

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
ID,111733,NaN,NaN,NaN,55867,32254.7,1,27934,55867,83800,111733
Nationality,111733,199,FRA,16516,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,107561,NaN,NaN,NaN,45.6392,17.245,-10,33,47,58,123
DaysSinceCreation,111733,NaN,NaN,NaN,595.027,374.657,36,288,522,889,1385
NameHash,111733,107584,0x15A713CE687991691A18F6CDC56ABE24979C73CF5D51...,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DocIDHash,110732,103480,0xE3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B...,3032,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AverageLeadTime,111733,NaN,NaN,NaN,60.8331,85.1153,-1,0,21,95,588
LodgingRevenue,111733,NaN,NaN,NaN,283.851,379.132,0,0,208,393.3,21781
OtherRevenue,111733,NaN,NaN,NaN,64.6828,123.581,0,0,31,84,8859.25
BookingsCanceled,111733,NaN,NaN,NaN,0.00228223,0.0806315,0,0,0,0,15
BookingsNoShowed,111733,NaN,NaN,NaN,0.000599644,0.0282168,0,0,0,0,3
BookingsCheckedIn,111733,NaN,NaN,NaN,0.737607,0.730889,0,0,1,1,76
PersonsNights,111733,NaN,NaN,NaN,4.32832,4.63074,0,0,4,6,116
RoomNights,111733,NaN,NaN,NaN,2.20383,2.30164,0,0,2,3,185
DistributionChannel,111733,4,Travel Agent/Operator,91019,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MarketSegment,111733,7,Other,63680,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SRHighFloor,111733,NaN,NaN,NaN,0.0425121,0.201755,0,0,0,0,1
SRLowFloor,111733,NaN,NaN,NaN,0.00130669,0.0361247,0,0,0,0,1
SRAccessibleRoom,111733,NaN,NaN,NaN,0.000223748,0.0149566,0,0,0,0,1
SRMediumFloor,111733,NaN,NaN,NaN,0.000769692,0.0277328,0,0,0,0,1
SRBathtub,111733,NaN,NaN,NaN,0.00313247,0.055881,0,0,0,0,1
SRShower,111733,NaN,NaN,NaN,0.00162888,0.0403267,0,0,0,0,1
SRCrib,111733,NaN,NaN,NaN,0.0161814,0.126173,0,0,0,0,1
SRKingSizeBed,111733,NaN,NaN,NaN,0.363268,0.480943,0,0,0,1,1
SRTwinBed,111733,NaN,NaN,NaN,0.156811,0.363624,0,0,0,0,1
SRNearElevator,111733,NaN,NaN,NaN,0.000331147,0.0181945,0,0,0,0,1
SRAwayFromElevator,111733,NaN,NaN,NaN,0.00359786,0.0598745,0,0,0,0,1
SRNoAlcoholInMiniBar,111733,NaN,NaN,NaN,0.000196898,0.0140307,0,0,0,0,1
SRQuietRoom,111733,NaN,NaN,NaN,0.087718,0.282886,0,0,0,0,1

Conclusions:
- There are 199 nationalities.
- There are 7 market segments.
- There 4 distribution channels.
- DocIDHash is missing one observation

In [5]:
# Check null values
ds.isnull().sum()

# Age has 4172 nulls and DocIDHash has 1001 nulls.
# All the other variables have no null values.

ID                         0
Nationality                0
Age                     4172
DaysSinceCreation          0
NameHash                   0
DocIDHash               1001
AverageLeadTime            0
LodgingRevenue             0
OtherRevenue               0
BookingsCanceled           0
BookingsNoShowed           0
BookingsCheckedIn          0
PersonsNights              0
RoomNights                 0
DistributionChannel        0
MarketSegment              0
SRHighFloor                0
SRLowFloor                 0
SRAccessibleRoom           0
SRMediumFloor              0
SRBathtub                  0
SRShower                   0
SRCrib                     0
SRKingSizeBed              0
SRTwinBed                  0
SRNearElevator             0
SRAwayFromElevator         0
SRNoAlcoholInMiniBar       0
SRQuietRoom                0
dtype: int64

In [6]:
# Check individuals with null values:
ds[ds['Age'].isnull() | ds['DocIDHash'].isnull()]

,ID,Nationality,Age,DaysSinceCreation,NameHash,DocIDHash,AverageLeadTime,LodgingRevenue,OtherRevenue,BookingsCanceled,...,SRMediumFloor,SRBathtub,SRShower,SRCrib,SRKingSizeBed,SRTwinBed,SRNearElevator,SRAwayFromElevator,SRNoAlcoholInMiniBar,SRQuietRoom
1,2,PRT,NaN,1385,0x198CDB98BF37B6E23F9548C56A88B00912D65A9AA0D6...,0xE3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B...,61,280.00,53.0,0,...,0,0,0,0,0,0,0,0,0,0
20,21,PRT,NaN,1385,0x792FE319C0867A1B48AED1DD032FAA5B0022E7FF5A35...,0xC3A80CBEDB77EE428047B97BE4FF5EF90D5A0AB5C2AC...,63,224.00,156.0,0,...,0,0,0,0,1,0,0,0,0,0
38,39,PRT,NaN,1385,0xF365E1EC454A18DB722D1DBD8886E027CD4B1234B8A9...,0xE3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B...,0,0.00,0.0,0,...,0,0,0,0,0,0,0,0,0,0
39,40,PRT,NaN,1385,0x581FBBDFCA174BB597E096E3A9CBED5E1A9FD615844B...,0xE3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B...,0,0.00,0.0,0,...,0,0,0,0,0,0,0,0,0,0
55,56,PRT,NaN,1385,0xD27550946D0D4D9A2C8ACABC25F3EB2E71340638AB58...,0xE3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B...,97,213.52,11.5,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111548,111549,PRT,NaN,39,0x7B3319EA712262C2CCB36BD025636C8D95C32846F125...,NaN,0,0.00,0.0,0,...,0,0,0,0,0,0,0,0,0,0
111552,111553,PRT,NaN,38,0xBC66C5A2A0C25C38CF99F5BF605A913382C4FF3B7960...,0xE3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B...,204,381.60,91.2,0,...,0,0,0,0,1,0,0,0,0,0
111630,111631,PRT,NaN,37,0xC3B0C105F99A992FAC2D08EC52356248A665821468CF...,NaN,0,0.00,0.0,0,...,0,0,0,0,0,1,0,0,0,0
111633,111634,PRT,NaN,37,0x32E38284BCC52BC1953CC30E2E18A673C42D38F7A2E0...,NaN,0,0.00,0.0,0,...,0,0,0,0,1,0,0,0,0,0
111634,111635,PRT,NaN,37,0x5841391089D0B9BCAE551C29A73484EE643542DB6881...,NaN,0,0.00,0.0,0,...,0,0,0,0,1,0,0,0,0,0

In [7]:
# Check if there are repeated rows with same NameHash and DocIDHash: these attributes should form an identifier of an individual so should not be repeated.
ds1=ds[['NameHash','DocIDHash']].drop_duplicates

In [8]:
# Do histograms on all numeric variables
numerical=ds.select_dtypes(include=[np.number]).columns.tolist()
ds[numerical].hist(bins=15, figsize=(15, 15), layout=(8,3), xlabelsize=8, ylabelsize=8);

In [9]:
# Number of individuals who canceled or did not show up by distribution channel:
ds.groupby(by=['DistributionChannel'])['BookingsCanceled','BookingsNoShowed'].mean()

                       BookingsCanceled  BookingsNoShowed
DistributionChannel
Corporate                      0.056459          0.017863
Direct                         0.003376          0.000355
GDS Systems                    0.001437          0.000000
Travel Agent/Operator          0.000220          0.000055

Para futura melhoria da segmentaÃ§Ã£o, deverÃ­amos ter acesso Ã  empresa que faz a marcaÃ§Ã£o. PoderÃ¡ haver diferenÃ§a de empresa para empresa.

In [24]:
import plotly.offline as pyo
import plotly.graph_objs as go

def scatter(df,var):
    df=pd.DataFrame(ds[var].value_counts())
    df=df.reset_index()
    df=df.rename(columns={'index':'count'})
    data=go.Scatter(x=df['count'],y=df[var],mode='markers')
    layout = go.Layout(title=var,template='simple_white',
            xaxis=dict(title=var,showgrid=True),yaxis=dict(title='Number of Individuals',showgrid=True))
    fig = go.Figure(data=data, layout=layout)
    pyo.plot(fig)
    
def hist(df,var):
    df=pd.DataFrame(ds[var].value_counts())
    df=df.reset_index()
    df=df.rename(columns={'index':'count'})
    data=go.Bar(x=df['count'],y=df[var])
    layout = go.Layout(title=var,template='simple_white',
            xaxis=dict(title=var,showgrid=True),yaxis=dict(title='Number of Individuals',showgrid=True))
    fig = go.Figure(data=data, layout=layout)
    pyo.plot(fig)

In [19]:
CatList=['Nationality','DistributionChannel', 'MarketSegment','SRHighFloor', 'SRLowFloor', 'SRAccessibleRoom', 'SRMediumFloor',
       'SRBathtub', 'SRShower', 'SRCrib', 'SRKingSizeBed', 'SRTwinBed',
       'SRNearElevator', 'SRAwayFromElevator', 'SRNoAlcoholInMiniBar',
       'SRQuietRoom']
NumList=['Age','DaysSinceCreation','NameHash','DocIDHash','AverageLeadTime','LodgingRevenue',
       'OtherRevenue','BookingsCanceled','BookingsNoShowed','BookingsCheckedIn','PersonsNights',
       'RoomNights']

In [16]:
# Get numerical variables in scatter plots:
for i in NumList:
    scatter(ds,i)

In [25]:
# Get categorical variables in bar charts:
for i in CatList:
    hist(ds,i)

Conclusions for each variable:<p>
<b>Age:</b> 
- Errors: There are individuals with negative ages and individuals with ages too low or too high to be real.
- Distribution is approximately normal which makes sense. Younger people do not book in hotel and older people tend to attend less hotels.  
- Number of people decreases with ages between 31 and 36 and then starts increasing again. From age 55, the number of people starts decreasing as age increases.

<b>DaysSinceCreation:</b>
- There are some points at which the difference of one day differentiates a lot the individuals that booked in the hotel. Reasons that might justify this are promotions or the increase of advertisements.

<b>NameHash:</b>
- there are individuals with the same NameHash: there are 3079 DocIDHash corresponding to more than 1 individual.

<b>DocIDHash:</b>
- there are individuals with the same DocIDHash: there are 3085 DocIDHash corresponding to more than 1 individual.

<b>DistributionChannel:</b>
- There are few individuals buying through GDS Systems.

In [41]:
# NameHash: how many NameHashes are repeated? 3079
df=pd.DataFrame(ds.NameHash.value_counts())
df[df['NameHash']!=1].count()

NameHash    3079
dtype: int64

In [42]:
# DocIDHash: how many DocIDHash are repeated? 3085
df=pd.DataFrame(ds.DocIDHash.value_counts())
df[df['DocIDHash']!=1].count()

DocIDHash    3085
dtype: int64